import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
//Hooks
import { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthUserContext';
//Roter
import { useRouter } from 'next/router';
//Components
import { CreateNote, NoteList } from '../components';

import RootLayout from '../layouts/RootLayout';

export default function archive() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lab Note</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://raw.githubusercontent.com/YsisC/DEV003-notes/main/public/assets/logo.svg" />
      </Head>
      <RootLayout>
        <div className='mx-1 md:mx-3'>

          <h1 className='primaryText mt-2 text-lg'>Notes</h1>
          <hr className='mt-1' />
          <div className='my-4'>
            <NoteList category={'notes'} value="notes" />
          </div>

          <h1 className='primaryText mt-2 text-lg'>Reminders</h1>
          <hr className='mt-1' />
          <div className='my-4'>

            <NoteList category={'reminders'} value="reminders" />
          </div>

        </div>


      </RootLayout>

    </div>
  )
}
