import Head from 'next/head'

//Css
import styles from '../styles/Home.module.css'
//Hooks
import { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthUserContext';
//Roter
import { useRouter } from 'next/router';
//Components
import Header from '../components/Header';
import CreateArea from '../components/CreateArea';
import NoteList from '../components/NoteList';
import Footer from '../components/Footer';
import RootLayout from '../layouts/RootLayout';

export default function Home(props) {

  //test autContext 2
  const { authUser, loading, } = useAuth();
  const router = useRouter();


  // Listen for changes on loading and authUser, redirect if needed
  useEffect(() => {
    if (!loading && !authUser)
      router.push('/login')
  }, [authUser, loading, router])

  // /show userData
  console.log(authUser)


  const [notes, setNotes] = useState([])
  // Save Notes function
  function addNote(newNote) {
    setNotes(prevValue => {
      // console.log("note", prevValue)
      return [...prevValue, newNote]
    })

  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Lab Note</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://raw.githubusercontent.com/YsisC/DEV003-notes/main/public/assets/logo.svg" />
      </Head>

      <RootLayout>
        <CreateArea />
        <NoteList value="notes" />
        {/* <NoteList value="cats" /> */}
      </RootLayout>

      <Footer></Footer>
    </div>
  )
}

// Home.Auth = WithPrivateRoute