import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import WithPrivateRoute from './components/WithPrivateRoute'

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <button onClick={props.logOut} className={styles.button} type="button">
                          Log out 
                        </button>
        <h1 class="text-3xl font-bold underline">
          Hello world!

        </h1>



      </main>

   
    </div>
  )
}

// Home.Auth = WithPrivateRoute