import Head from 'next/head'
import Image from 'next/image'

//Css
import styles from '../styles/Home.module.css'
//Hooks
import { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthUserContext';
//Roter
import { useRouter } from 'next/router';
//Components
import { CreateNote, NoteList, Modal } from '../components';
import RootLayout from '../layouts/RootLayout';




export default function Reminders(props) {
  const { authUser, loading } = useAuth();
  const router = useRouter();

   // Listen for changes on loading and authUser, redirect if needed
  useEffect(() => {
    if (!loading && !authUser)
      router.push('/login')
  }, [authUser, loading, router])


  return (
    <div className={styles.container}>
    <Head>
      <title>Lab Note</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="https://raw.githubusercontent.com/YsisC/DEV003-notes/main/public/assets/logo.svg" />
    </Head>
    <RootLayout>
      <CreateNote category={'reminders'}  authUser={authUser} />
      <NoteList category={'reminders'} value="reminders" />
   
    </RootLayout>

  </div>
  )
}
